# Generated by Django 5.2 on 2025-05-14 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='th_order_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transactionhistory'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='th_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('RETURN_SALE', 'Sales Return'), ('RETURN_PURCHASE', 'Purchase Return'), ('USAGE', 'Internal Usage'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('ADJUSTMENT', 'Adjustment'), ('EXPENSE', 'Expense'), ('ORDERIN', 'Order in'), ('ORDEROUT', 'Order out')], max_length=50),
        ),
    ]
