# Generated by Django 5.2 on 2025-04-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
