# Generated by Django 5.2 on 2025-05-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transactionhistory_th_order_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='th_retur',
            new_name='th_return_reference',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='th_so',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='th_return',
            field=models.BooleanField(default=False),
        ),
    ]
