# Generated by Django 5.2 on 2025-05-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_th_retur_transactionhistory_th_return_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitemdetail',
            name='stock_price_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transitemdetail',
            name='stock_price_buy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
