# Generated by Django 5.2 on 2025-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pointtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitemdetail',
            name='stock_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
