# Generated by Django 5.2 on 2025-05-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transitemdetail_stock_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transitemdetail',
            old_name='stock_change',
            new_name='stock_quantity',
        ),
    ]
