# Generated by Django 5.2 on 2025-06-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_stock_change_transitemdetail_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitemdetail',
            name='stock_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
