# Generated by Django 5.2 on 2025-06-11 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transitemdetail_stock_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='araptransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 11, 16, 30, 38, 74313)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='araptransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
