# Generated by Django 5.2 on 2025-06-17 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_payment_customer_payment_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='araptransaction',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.araptransaction'),
        ),
    ]
