# Generated by Django 5.2 on 2025-06-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_araptransaction_is_closed_alter_payment_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='araptransaction',
            name='is_closed',
        ),
    ]
