# Generated by Django 5.2 on 2025-07-10 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_araptransaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.transactionhistory'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_history'], name='api_payment_transac_3712b3_idx'),
        ),
    ]
