# Generated by Django 5.2 on 2025-07-16 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_payment_transaction_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='api.account'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='api.account'),
        ),
    ]
