# Generated by Django 5.2 on 2025-07-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_transactionhistory_from_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='th_type',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='th_types',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='api.transactiontype'),
        ),
    ]
